[project]
name = "bot-or-not"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.119.1",
    "msgspec>=0.19.0",
    "sqlmodel>=0.0.27",
    "python-dotenv>=1.0.0",
]
